language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

before_install:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -v github.com/golobby/config -coverprofile=config.coverprofile
  - gover
  - goveralls -race -coverprofile gover.coverprofile -service travis-ci

notifications:
  email:
    recipients:
      - info@miladrahimi.com
    on_success: change
    on_failure: always
